### ISSUE TITLE
css 256个选择器越级

### ISSUE THREAD

**Issue by 117sparta** [117sparta/blogs#13]
目前这种越级现象只有在IE浏览器才会出现，例如：
```html
<span id="foo" class="f">颜色是？</span>
```
```css
#foo {
  color: #000;
  background: #eee;
}
.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f.f........(此处省略，总共256次） {
  color: #fff;
  background: #333;
}
```

这时候IE浏览器的表现是color: #fff，background: #333，表示256个类选择器优先级的累加超过了id选择器。
