### ISSUE TITLE
无效css选择器特性与实际应用

### ISSUE THREAD

**Issue by 117sparta** [117sparta/blogs#14]
有很多css伪类选择器是近几年才出现的，浏览器并不支持，浏览器会把这些选择器当作无效的选择器。但是当无效的选择器和其他有效的选择器写在一起的时候，会导致整个选择器无效。例如：
``` css
.example:hover,
.example:active,
.example:focus-within {
  color: red;
}
```
:hover和:active这两个，老早就出现了，正常来讲，所有浏览器都能识别这两个伪类。但是focus-within在IE浏览器中不支持，所以在IE浏览器中上面整个选择器无效。

这种特性带来一个好处，可以**通过这种结合来区分不同浏览器的样式**，实现渐进式增强。例如：
``` css
/* IE 浏览器生效 */
.example:hover,
.example:active {
  color: black;
}

/* IE 浏览器失效，但是其他浏览器生效 */
.example:hover,
.example:active,
.example:focus-within {
  color: red;
}
```

不过，在诸多css选择器中，这种无效选择器特性出现了一个例外，那就是浏览器可以识别以-webkit-私有前缀开头的css伪元素。例如，下面这段css在正常情况下是无效的：
``` css
div, span::whatever {
  background: gray;
}
```
但是，如果加上-webkit-，这时候除了IE浏览器外的其他浏览器（Firefox在version 63以上）可以正常识别。
```
div,span::-webkit-whatever {
  background: gray;
}
```
基于此，我们可以用这项特性来区分IE浏览器和其他浏览器。
