### ISSUE TITLE
css选择器优先级

### ISSUE THREAD

**Issue by 117sparta** [117sparta/blogs#15]
> 摘选自《css选择器世界》

CSS优先级有着明显的不可逾越的等级制度，我将其划分为0-5这6个等级，其中前4个等级由CSS选择器决定，后2个等级由书写形式和特定语法决定。下面我将对这6个等级分别进行讲解。

（1）0级：通配选择器、选择符和逻辑组合伪类。其中，通配选择器写作星号（*）。示例如下：
``` css
* { color: #000; }
```
选择符指的是+，~,  >, 空格, 和||。
逻辑组合伪类有:not(), :is(), :where()等，这些伪类本身并不影响css的优先级。影响优先级的是括号里面的选择器。
``` css
:not(.example1) { }
```
需要注意的是，只有逻辑组合伪类的优先级是0，其他伪类的优先级并不是这样的。

（2）1级。标签选择器。示例如下：
``` css
div { color: black; }
```

（3）2级。类选择器、属性选择器和非逻辑伪类。示例如下：
``` css
.foo { color: #666; }
[hidden] { color: #666; }
:hover { color: #333; }
```

（4）3级。ID选择器。示例如下：
``` css
#example {}
```

（5）4级。style属性内联。示例如下：
``` html
<span style="color: #ccc;"></span>
```

（6）5级。!important。（非常不推荐使用）示例如下：
``` css
.foo { color: #fff !important; }
```
