### ISSUE TITLE
Grid网格布局

### ISSUE THREAD

**Issue by 117sparta** [117sparta/blogs#54]
### 基础使用
1. 外部容器使用display: grid，这个容器即转变为网格容器。
2. 用grid-template-rows和grid-template-columns定义多少行多少列，每行或者每列使用空格分隔。
3. 然后这个容器内部的项就会自动排布。

```html
// html
<div class="grid-container">
  <div class="item">1</div>
  <div class="item">2</div>
  <div class="item">3</div>
  <div class="item">4</div>
  <div class="item">5</div>
  <div class="item">6</div>
  <div class="item">7</div>
  <div class="item">8</div>
</div>
```
```css
// css
.grid-container {
  display: grid;
  grid-template-rows: 100px 100px;
  grid-template-columns: 1fr 1fr 1fr;
}
.item {
  border: 1px solid black;
  margin: 5px;
}
```

显示结果如下：
![image](https://user-images.githubusercontent.com/37238800/160060212-6bb678ba-b482-430d-98cd-c3535e60f157.png)

基础使用就这样了，可以很方便的解决九宫格的面试题。不过解决这个问题也可以用flex：
```css
.flex-grid {
  display: flex;
  flex-wrap: wrap;
  margin-top: 20px;
  background-color: aqua;
}
.flex-item {
  flex: 1 1 31.33%;
  border: 1px solid black;
  margin: 0.4%;
}
```
```html
<div class="flex-grid">
  <div class="flex-item">1</div>
  <div class="flex-item">2</div>
  <div class="flex-item">3</div>
  <div class="flex-item">4</div>
  <div class="flex-item">5</div>
  <div class="flex-item">6</div>
  <div class="flex-item">7</div>
  <div class="flex-item">8</div>
  <div class="flex-item">9</div>
</div>
```

### 显式网格和隐式网格
如果定义了一个2x3的网格布局，那么这个6个格子就是显式网格。但是如果里面的内容超出了6个，那么网格布局会自动创建隐式网格，把这些超出的内容放到隐式网格内。基础使用中的第7和第8个网格就是隐式网格，这时行高并不是设定的100px，而是元素的高度。

### grid-template-columns
这个属性主要是定义列数以及每列的宽度。基础写法：`grid-template-columns: 100px 100px 100px;` 。
使用：
1. 使用数值加正确的css单位定义宽度或者使用一些内设值。例如`grid-template-columns: 100px 100px 100px;`
2. 每列之间用空格隔开。
3. 可以用repeat减少重复值的编写。例如`grid-template-columns: repeat(3, 100px);`定义三列，每列100px。也可以`grid-template-columns: 200px repeat(3, 100px) 10%;`这样子定义5列，中间三列相同。
4. 可以使用minmax定义一列的最小和最大宽度，如果可以达到最大宽度，那么会达到最大宽度。例如`grid-template-columns: minmax(100px, 200px) 100px 100px;`。
5. 可以使用特殊的 <strong>数值 + fr</strong> 来定义一列的增长数值，参考flex-grow。例如`grid-template-columns: 1fr 1fr 1fr;`表示三等分。
6. 可以使用内设值max-content表示这一列宽度无限，连续的内联内容越多，宽度越大。
7. 可以使用内设值min-content，min-content尝试尽可能的不让内容overflow，如果连续的内联内容可以换行，那么这个选项会让它换行。注意如果无法换行，那么宽度也会随连续的内联内容增多而增多。
8. 可以使用内设值auto，表示获取剩下的所有空间，如果多列设置成这个，那么剩余空间会等分。
9. 如果fr和auto混用，并且所有的fr加起来大于等于1，那么fr的列会占据尽可能大的空间，auto指定的列宽会变成内容的宽度。
10. 如果fr和auto混用，并且所有的fr加起来小于1，那么fr的列宽会变成**（父元素宽度 - auto列的内容宽度）* fr的小数数值**，然后auto列挤满剩下的空间。

第1点和第3点示例：
![image](https://user-images.githubusercontent.com/37238800/160097647-003e7e13-3108-4332-97e9-818bfaa04d04.png)

第4点`grid-template-columns: minmax(100px, 200px) 100px 100px;`示例：
![image](https://user-images.githubusercontent.com/37238800/160098094-1c0fe0fa-fdb4-4aaa-b06c-d18cc0d4b2e6.png)
可以看到容器宽度足够的情况下，保持为200px的最大宽度。如果容器宽度足够小，那么会保持100px，如下图。
![image](https://user-images.githubusercontent.com/37238800/160098559-7cb8f54f-6eb4-4ae9-b3bd-f0cc78cf31cc.png)

第5点示例：
`grid-template-columns: 1fr 1fr 1fr;`
![image](https://user-images.githubusercontent.com/37238800/160098745-c29590eb-ffa1-416a-b1b7-70cbea488c70.png)

`grid-template-columns: 1fr 2fr 1fr;`
![image](https://user-images.githubusercontent.com/37238800/160098857-2c7bb4d1-1915-44ae-bb2e-1193aab92050.png)

第6点和第7点示例：
`grid-template-columns: min-content 100px max-content;`
```html
// html 如下：
<div class="div-ele">
  <div class="item">djflakjdlkfj alkdjldskjflkajdlkfjaldjflakdjflkja lkfjaldskjflkasdjfl kadsjfkldj falksjfkldsjfdkjfl ajldjf ljjflkajdlkfjalkdj</div>
  <div class="item">2</div>
  <div class="item">3<br/>djflakjdlkfj alkdjldskjflkajdlkfjaldjflakdjflkja lkfjaldskjflkasdjfl kadsjfkldj falksjfkldsjfdkjfl ajldjf ljjflkajdlkfjalkdj</div>
  <div class="item">4</div>
  <div class="item">5</div>
  <div class="item">6</div>
  <div class="item">7</div>
  <div class="item">8</div>
</div>
```
![image](https://user-images.githubusercontent.com/37238800/160115744-6ee756ea-4bd5-4944-a45e-1daba8686dc3.png)
可以看到第一列min-content会让连续的文字换行来让内容不超出，但是max-content则是直接不换行。

第8点示例：
`grid-template-columns: auto 100px auto;`
![image](https://user-images.githubusercontent.com/37238800/160116144-f61e1415-7243-4f1a-bfe2-79517d40879b.png)

第9点示例：
`grid-template-columns: auto .5fr .5fr;`
![image](https://user-images.githubusercontent.com/37238800/160138413-747acb13-afec-4d96-8441-94273273fc23.png)

第10点示例：
`grid-template-columns: auto .4fr .4fr;`
![image](https://user-images.githubusercontent.com/37238800/160138750-ce36d50e-5f3e-4af4-b385-17ceda862936.png)

### grid-template-rows
用法和grid-template-columns一致，不过如果父元素没有设高度，那么使用弹性单位（fr）无效。当没有设置高度，并且使用百分比的话，那么会按照容器内容高度进行计算。举个例子，下面这个图是没有设置grid-template-rows的情况（高度99）：
![image](https://user-images.githubusercontent.com/37238800/160136034-7e0ef64e-6017-43d5-af27-60c44066d0a8.png)

然后设置`grid-template-rows: 50% 50%;`，会变成这样（高度还是99，不过第三行被挤出去了），这时候第一行和第二行各占容器高度的一半：
![image](https://user-images.githubusercontent.com/37238800/160136324-2780a987-9b8e-4015-843f-d8a3a26b7773.png)

### 来看看网格线
网格布局，除了网格本身之外，网格线也很重要。网格线可以用来合并单元格。例如：
```css
.div-ele {
  background-color: red;
  display: grid;
  grid-template-rows: 100px 100px 100px;
  grid-template-columns: 100px 100px 100px;
}
.item1 {
  /*这个占据左上角四个格子*/
  border: 1px solid black;
  margin: 5px;
  grid-column-start: 1;
  grid-column-end: 3;
  grid-row-start: 1;
  grid-row-end: 3; 
  /*
   合并
   grid-column: 1 / 3;
   grid-row: 1 / 3;
   语法是：grid-start / grid-end | grid-start
  */
  /*
   再合并
   grid-area: 1 / 1 / 3 / 3;
   语法是：grid-row-start / grid-column-start / grid-row-end / grid-column-end
  */
  /*
    或者可以这样，span表示横跨多少条线
    grid-column-start: span 2;
    grid-row-start: span 2;
   */
}
.item {
  border: 1px solid black;
  margin: 5px;
}
```
效果如下：
![image](https://user-images.githubusercontent.com/37238800/160141603-cea83cd3-a1d8-4e10-8830-8ce294e79cae.png)

另外网格线在使用grid-template-rows和grid-template-columns的时候可以进行命名（不过在item1使用的时候貌似没效果...Chrome浏览器）：
```css
.div-ele {
  grid-template-columns: [ columnline1 columnline2 columnline3 columnline4] 100px 100px 100px;
  grid-template-columns: [ rowline1 rowline2 rowline3 rowline4] 100px 100px 100px;
}
.item1 {
  /*这个占据左上角四个格子*/
  border: 1px solid black;
  margin: 5px;
  grid-column-start: columnline1;
  grid-column-end: columnline3;
  grid-row-start: rowline1;
  grid-row-end: rowline3; 
}
```

### grid-template-areas
如果整个区域会进行完整划分，那么建议使用这个属性。如果只是几个需要合并为一个区域，那么还是用grid-row和grid-column比较好。
详情可以看这个：[grid-template-areas mdn](https://developer.mozilla.org/zh-CN/docs/Web/CSS/grid-template-areas)

### 和flex的不同之处
flex是轴性布局，也就是是一维的，但是grid是二维的。

### 参考：
[CSS Grid 网格布局教程 -- 阮一峰](https://www.ruanyifeng.com/blog/2019/03/grid-layout-tutorial.html)
[mdn display grid](https://developer.mozilla.org/zh-CN/docs/Glossary/Grid)
[张鑫旭 grid布局](https://www.zhangxinxu.com/wordpress/2018/11/display-grid-css-css3/)
