### ISSUE TITLE
CSS 实现垂直水平居中

### ISSUE THREAD

**Issue by 117sparta** [117sparta/blogs#78]
使用CSS实现垂直水平居中的方式：
## 通用
```css
// 第一种
.parent {
  display: flex;
  align-items: center;
  justify-content: center;
}

// 第二种
.parent {
  position: relative;
}
.child {
  position: absolute;
  top: 100px;
  left: 50px;
  right: 50px;
  bottom: 100px;
}
```

## 子元素是内联盒子：
```css
// 第一种
.parent {
  text-align: center;
  line-height: 父元素高度;
}

// 第二种
.parent {
  display: table-cell;
  vertical-align: middle;
  text-align: center;
}
```

## 子元素是块级元素
```css
// 第二种，出处https://csscoco.com/inspiration/#/./layout/best-way-to-center-element
.parent {
  display: flex;
}
.child {
  width: 40px;
  height: 40px;
  margin: auto;
}
```
